### ISSUE TITLE
Mac Build fails for JdeRobot/darknet on Travis CI

### ISSUE THREAD

**Issue by vinay0410** [JdeRobot/dl-DetectionSuite#115]
JdeRobot/darknet would be deprecated soon, but for now, a quick fix for the same would be very helpful.
Link to Travis CI build: https://travis-ci.org/JdeRobot/dl-DetectionSuite/builds/504615405?utm_source=github_status&utm_medium=notification

**Comment by sleep-404** [comment]
I think this is the primary reason because of which the the build fails whenever someone tries to send a PR. So I guess this should be fixed before working on shifting logs to glogs because in the end even that would result in failure of the build.
So if darknet is causing the problem which I guess is the backend for this project , would shifting to Tensorflow solve the issue ?

**Comment by vinay0410** [comment]
This project uses multiple frameworks like darknet, tensorflow, keras and caffe. TensorFlow and Keras are runtime dependencies, whereas darknet and caffe are built at build time also.

We are using JdeRobot/darknet, which needs to be fixed for successful travis builds. [Pull Request](https://github.com/JdeRobot/darknet/pull/5) for the same is already open, I will get it merged.

**Comment by vinay0410** [comment]
Fixed
