### ISSUE TITLE
Include support to COCO dataset format

### ISSUE THREAD

**Issue by chanfr** [JdeRobot/dl-DetectionSuite#5]

**Comment by vinay0410** [comment]
Hi @chanfr ,
This is regarding parsing JSON files using COCO dataset, and since we have agreed on using rapidjson. I would like to mention that rapidjson is already a dependency in Darknet Fork and DetectionSuite.

So, we can continue to write code using rapidjson, or if neccesary, we can also remove this external dependency. 
Since it is header only library, it can be directly used in our code without the need to be installed. This way we can maintain its version compatibility since users might have different version installed.

Which way do you think is the best way to go ?

Also, COCODatasetReader is almost complete just running some tests.
