### ISSUE TITLE
Request for tutorial to run detector

### ISSUE THREAD

**Issue by akhilkumarco007** [JdeRobot/dl-DetectionSuite#64]
Is there any way to save the inference files that we get with deployer? I want to save the bounding boxes and the frames of the video. I really appreciate if you can help me know it.

**Comment by vinay0410** [comment]
Hi @akhilkumarco007 ,
Sorry, for the late reply.
Actually, Deployer only runs inferences and doesn’t store it currently.
You can use Detector if you want to store images in any particular dataset format.

Though, that would be a nice feature, if deployer could store images also.
I would certainly add that feature.
Any suggestion, in which format you require it to be stored.

Also, Don’t hesitate to ask anything about DetectionSuite,

Just one more thing, I assume that you have already installed DetectionSuite, so how easy was the installation part :smiley:

Thanks, and I will add this option in day

**Comment by vinay0410** [comment]
Also, see aour wili for more details on various tools.

**Comment by akhilkumarco007** [comment]
Hi Vinay,
Thank you for your response! I wanted to try detector but didn't know what I should provide for the input dataset as I just have raw frames. Thank you for willing to add that feature, I think it will be really helpful to a lot of people. For my use, I would like the output of the deployer to be the frames and the bounding boxes to be saved in a JSON file. 
I have installed DetectionSuite, I faced serious issues with OpenCV but in the end, managed to make it work. I am not an experienced user of Linux so I found your tutorial a bit tougher to follow. I think sometimes it assumes that the user knows but it was not true in my case. Also, I didn't know how to run the app until I read the wiki, maybe moving some parts of wiki instructions on how to start the app and the link to your demonstration video to README would help a lot of new users of Linux. 

I think the work you have done is really valuable and please keep up the good work. Thank you so much for the tool and I really appreciate your hard work in making this tool.

**Comment by vinay0410** [comment]
Hi @akhilkumarco007 ,
Sorry, for bugs in installation instructions, I have updated them and submitted a pull request.
Also, Opencv3.4 is only necessary if you require caffe support, otherwise 2.4 is sufficient and can be installed with a single command as mentioned ```sudo apt-get install libopencv-dev```.

And, for JSON we have 2 formats one is COCO, it will save all the details in a single file, and the other is our own json which will create a json file for each image.
I will add support for all of them, you can choose any one according to your preference.

**Comment by akhilkumarco007** [comment]
Hi Vinay,
The problem with open cv occurred during DL suite installation. It asked for opencv to direct to something and as my open cv installation didn't point to anything, it was considered to be not found. I couldn't fix it no matter what I did. In the end, I had to reinstall ubuntu and install everything from scratch to make it work. I think it might be system specific but not sure why it happened. 

Thank you for planning to add the requested features. :)

**Comment by vinay0410** [comment]
Oh, I am very sorry you had to face that, and reinstall ubuntu.
I didn't completely understand what installation had to point to.
If you face any such issue in the future, just create an issue here, and we'll help, and hopefully without reinstalling anything :smiley: 

Also, I have added the feature, you requested and it has been merged.
So just pull again, and it would work.

It would store both images, and data such as bounding boxes, confidence scores and classIds, in the specified folder. Multiple json files would be written each a single image containing all its detections.

I have also made a sample video depicting the new functionality, just have a look.
[https://www.youtube.com/watch?v=xX2c_Trp9qY](https://www.youtube.com/watch?v=xX2c_Trp9qY)

Just ask, if you face any problem.

Cheers

**Comment by akhilkumarco007** [comment]
Sure, Thanks for the video. It helps a lot!

**Comment by vinay0410** [comment]
Hi @akhilkumarco007 ,
Since you've closed this issue, I hope that your problem was resolved.
Also, now we have a new tutorial containing videos and step by step instructions about starting with DatasetEvaluationApp.
You can refer to it if you wish to learn more about our tool.
[Beginner's Tutorial Part 1](https://github.com/JdeRobot/dl-DetectionSuite/wiki/Beginner's-Tutorial-to-DetectionSuite-Part-1)

Also, Deployer has been enhanced to support live alteration of Confidence Threshold ( it was 0.2 by default earlier ), and would be merged soon.
Thanks
